<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

?>
<div class="login-container">
    <h1 class="center" style="margin-bottom:0;">
        FORGOT PASSWORD
    </h1>
    <div class='block block-customer-login'>
        <form class="form password forget"
              action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/forgotpasswordpost') ?>"
              method="post"
              id="form-validate"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                <div class="field note"><?php /* @escapeNotVerified */ echo __('Please enter your email address below to receive a password reset link.'); ?></div>
                <div class="field email required" style="margin-bottom: 10px;">
                    <div class="control">
                        <input type="email" name="email" alt="email" id="email_address" placeholder="Email Address" class="input-text" value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="actions-toolbar">
                    <div class="primary" style="margin-bottom: 11px;">
                        <button type="submit" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('Submit') ?></span></button>
                    </div>
                    <div class="secondary">
                        <a class="action go-back" href="<?php /* @escapeNotVerified */ echo $block->getLoginUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
                    </div>
                </div>
            </fieldset>
            
        </form>
    </div>
</div>
