<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<?php if(@$_GET['message'] == "account_not_approved"): ?>
<div class="ekr-message" id="account_not_approved">
    <i class="fa fa-exclamation"></i> Before you can continue, your account must be approved by one of our customer service representitives.
</div>
<?php endif; ?>
<h1 class="center" style="margin-bottom:0;">
    Login
</h1>
<div class="block block-customer-login">
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?php echo $block->getBlockHtml('formkey'); ?>
            <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ //echo __('* Required Fields') ?>">
                <div class="field note"><?php /* @escapeNotVerified */ //echo __('If you have an account, sign in with your email address.') ?></div>
                <div class="field email required" style="margin-bottom:10px;">
                    <div class="control">
                        <input name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}" placeholder="Email Address" />
                    </div>
                </div>
                <div class="field password required" style="margin-bottom:15px;">
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true, 'validate-password':true}" placeholder="Password" />
                    </div>
                </div>
                <?php echo $block->getChildHtml('form_additional_info'); ?>
                <div class="actions-toolbar">
                    <div class="primary" style="margin-bottom: 10px;"><button type="submit" class="action login primary" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('Login') ?></span></button></div>
                    <div class="primary" style="margin-bottom: 10px;"><a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Password') ?></span></a></div>
                    <div class="primary" style="margin-bottom: 10px;"><a class="action remind" href="/store/customer/account/create/"><span><?php /* @escapeNotVerified */ echo __('Request Account') ?></span></a></div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
