<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$_order = $block->getOrder();

?>
<?php /** @var  $block \Magento\Sales\Block\Order\View */?>
<div class="order-owner"><?php echo $block->getStoreName($_order->getCustomerId()) . " : " . $_order->getCustomerName(); ?></div>
<div class="order-details-items ordered">
    

    <div class="order-title">
        <strong><?php /* @escapeNotVerified */ echo __('Items Ordered') ?></strong>
        <?php if ($_order->getTracksCollection()->count()) : ?>
            <?php echo $block->getChildHtml('tracking-info-link') ?>
        <?php endif; ?>
    </div>

    <?php echo $block->getChildHtml('order_items') ?>

    <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order', $_order) && $_order->getGiftMessageId()): ?>
    <div class="block block-order-details-gift-message">
        <div class="block-title"><strong><?php /* @escapeNotVerified */ echo __('Gift Message for This Order') ?></strong></div>
        <?php $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessageForEntity($_order); ?>
        <div class="block-content">
            <dl class="item-options">
                <dt class="item-sender"><strong class="label"><?php /* @escapeNotVerified */ echo __('From') ?></strong><?php echo $block->escapeHtml($_giftMessage->getSender()) ?></dt>
                <dt class="item-recipient"><strong class="label"><?php /* @escapeNotVerified */ echo __('To') ?></strong><?php echo $block->escapeHtml($_giftMessage->getRecipient()) ?></dt>
                <dd class="item-message"><?php /* @escapeNotVerified */ echo $this->helper('Magento\GiftMessage\Helper\Message')->getEscapedGiftMessage($_order) ?></dd>
            </dl>
        </div>
    </div>
    <?php endif; ?>
    <?php if($block->canApprove()): ?>
        <div class="block ekr_eauth">
            <div class='block-title'><strong><?php echo __('Order Authorization'); ?></strong></div>
            <div class="block-content">
                <?php $eauth = $block->getEauth();
                if(empty($eauth['signature_image_data'])):
                    $tokenUrl = "http://" . $_SERVER['HTTP_HOST'] . "/lashbrook-order-verification/". $eauth['eauth_token']; ?>
                    <div class="ekr_attention">
                        Before we can process your order, you must authorize it.<br><br> Please visit <a href="<?php echo $tokenUrl; ?>" target="_blank"><?php echo $tokenUrl; ?></a> to provide an e-signature.
                    </div>
                <?php else: ?>
                        <?php echo __('Thank you for providing your signature'); ?>
                        <div class="ekr_esignature"><img src="<?php echo $eauth['signature_image_data']; ?>"/></div>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
    <div class="actions-toolbar">
        <div class="secondary">
            <a class="action back" href="<?php /* @escapeNotVerified */ echo $block->getBackUrl() ?>">
                <span><?php /* @escapeNotVerified */ echo $block->getBackTitle() ?></span>
            </a>
        </div>
    </div>
</div>
