<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php foreach ($block->getChildHtmlList() as $_html): ?>
    <?php /* @escapeNotVerified */ //echo $_html ?>
<?php endforeach; ?>
<img src="/store/pub/media/images/lone-star.png" class="separator-image" alt="Separator" />
<h4 class="center" style="margin-bottom:20px;">you might also like</h4>
<div class="ring-collection">
    <img class="left-fader" src="/store/pub/media/images/rings/fader.png">
    <img class="right-fader" src="/store/pub/media/images/rings/fader.png">
    <div class="left-arrow" style=""><i class="fa fa-angle-left"></i></div>
    <div class="right-arrow" style=""><i class="fa fa-angle-right"></i></div>
    <div class="rings-holder" id="ring-holder" style="left: -363px;">
        <img class="ring ring0" src="/wp-content/uploads/2017/02/featured-ring-_0004_ZHW8D15_ARGOSAGEORANGE.png" alt="ZHW8D15/OSAGEORANGE POLISH" data-link="/store/meteorite-ring.html">
    <img class="ring ring1" src="/wp-content/uploads/2017/02/featured-ring-_0005_ZHW8B15NS_LEOPARD.png" alt="ZHW8B15(NS)/LEOPARD" data-link="/store/meteorite-ring.html">
    <img class="ring ring2" src="/wp-content/uploads/2017/02/featured-ring-_0006_HWSLEEVED9D13_14KY_OSAGE.png" alt="HWSLEEVED9D13/14KY/OSAGEORANGE" data-link="/store/meteorite-ring.html">
    <img class="ring ring3" src="/wp-content/uploads/2017/02/featured-ring-_0007_HWSLEEVE14KR8FR_NATCOCODISTRESS.png" alt="HWSLEEVE14KR8FR/NATCOCO DISTRESSED" data-link="/store/meteorite-ring.html">
    <img class="ring ring4" src="/wp-content/uploads/2017/02/featured-ring-_0008_HWSLEEVCC7D_LCVTREES_BOXELDERSATIN.png" alt="HWSLEEVCC7D/LCVTREES/BOXELDERBURL SATIN" data-link="/store/meteorite-ring.html">
    <img class="ring ring5" src="/wp-content/uploads/2017/02/featured-ring-_0002_HW8B16NS_MAPLEWHIRL.png" alt="HW8B16(NS)/MAPLEBURL POLISH" data-link="/store/meteorite-ring.html">
    <img class="ring ring6" src="/wp-content/uploads/2017/02/featured-ring-_0009_Hardwood.png" alt="HWSLEEVED8D/REDHEART ACID" data-link="/store/meteorite-ring.html">
    <img class="ring ring7" src="/wp-content/uploads/2017/02/featured-ring-_0003_CCHW9F13OC_BOXELDERBURL.png" alt="CCHW9F13OC/BOXELDERBURL POLISH" data-link="/store/meteorite-ring.html">
    <img class="ring ring9 ring8" src="/wp-content/uploads/2017/02/featured-ring-_0001_18KYHW8FGEW2UMIL14DESERTIRONWOODBURL.png" alt="14KY8FGEW2UMIL14/DIWBURL POLISH" data-link="/store/meteorite-ring.html">

        <div class="ring-data">
            <a class="ring-name" href="/store/meteorite-ring.html">HWSLEEVE14KR8FR/NATCOCO DISTRESSED</a>
            <a href="/store/meteorite-ring.html" class="ring-link">View <i class="fa fa-caret-right"></i></a>
        </div>
    </div>
</div>
<script src="/wp-content/themes/rinzler/js/ringcollection.js"></script>
<script>

   var ringColl = new RingCollection(document.querySelector(".ring-collection"));

</script>