<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php foreach ($block->getChildHtmlList() as $_html): ?>
    <?php /* @escapeNotVerified */ //echo $_html ?>
<?php endforeach; ?>
<img src="/store/pub/media/images/lone-star.png" class="separator-image" alt="Separator" />
<h4 class="center" style="margin-bottom:20px;">you might also like</h4>

<div class="ring-collection">
    <img class="left-fader" src="/store/pub/media/images/rings/fader.png">
    <img class="right-fader" src="/store/pub/media/images/rings/fader.png">
    <div class="left-arrow" style=""><i class="fa fa-angle-left"></i></div>
    <div class="right-arrow" style=""><i class="fa fa-angle-right"></i></div>
    <div class="rings-holder" id="ring-holder">
        <img class="ring ring0" src="https://lashbrook.elikirk-dev.com/wp-content/uploads/2016/02/CCPF9FSQ16_ZIRCONIUMHAMMER_POLISH001.png" alt="CCPF9FSQ16/ZIRCONIUM HAMMER/POLISH" data-link="/store/catalog/product/view/id/190768/?base_metal=10&amp;inlay=31&amp;finish=15">
        <img class="ring ring1" src="https://lashbrook.elikirk-dev.com/wp-content/uploads/2016/02/CC9FGECROSSSATIN_POLISH001.png" alt="CC9FGE CROSS SATIN/POLISH" data-link="store/catalog/product/view/id/59/?category_id=5&amp;base_metal=19&amp;finish=18&amp;weight=291">
        <img class="ring ring2" src="https://lashbrook.elikirk-dev.com/wp-content/uploads/2016/02/CC7.5F14_METEORITE_MGAPOLISH001.png" alt="CC7.5F14/METEORITE/MGA POLISH" data-link="store/catalog/product/view/id/59/?category_id=5&amp;base_metal=19&amp;finish=18&amp;weight=291">
        <img class="ring ring3" src="https://lashbrook.elikirk-dev.com/wp-content/uploads/2016/02/CC7.5FGEW2UMIL13_14KRHAMMER_POLISH001.png" alt="CC7.5FGEW2UMIL13/14KR HAMMER/POLISH" data-link="store/catalog/product/view/id/78841/?base_metal=10&amp;inlay=73&amp;finish=15">
        <img class="ring ring4" src="https://lashbrook.elikirk-dev.com/wp-content/uploads/2016/02/CC7D_LCVFINGERPRINT2SATIN001.png" alt="CC7D/LCVFINGERPRINT2 SATIN" data-link="store/catalog/product/view/id/92663/?base_metal=10&amp;finish=40">
        <img class="ring ring5" src="https://lashbrook.elikirk-dev.com/wp-content/uploads/2016/02/CC8FGECELTIC6CROSSSATIN_POLISH001.png" alt="CC8FGECELTIC6 CROSS SATIN/POLISH" data-link="store/catalog/product/view/id/59/?category_id=5&amp;base_metal=19&amp;finish=18&amp;weight=291">
        <img class="ring ring6" src="https://lashbrook.elikirk-dev.com/wp-content/uploads/2016/02/CC7F_LCVSOUNDWAVESATIN001.png" alt="CC7F/LCVSOUNDWAVE SATIN" data-link="store/catalog/product/view/id/59/?category_id=5&amp;base_metal=19&amp;finish=18&amp;weight=291">
        <img class="ring ring7" src="https://lashbrook.elikirk-dev.com/wp-content/uploads/2016/02/CC8REFDBSTRIPECROSSSATIN_POLISH001.png" alt="CC8REFDBSTRIPE CROSS SATIN/POLISH" data-link="store/catalog/product/view/id/59/?category_id=5&amp;base_metal=19&amp;finish=18&amp;weight=291">
        <img class="ring ring8" src="https://lashbrook.elikirk-dev.com/wp-content/uploads/2016/02/CCPF7F15_FLATTWISTACID_POLISH001.png" alt="CCPF7F15/FLATTWIST ACID/POLISH" data-link="store/catalog/product/view/id/96892/?base_metal=10&amp;inlay=35&amp;finish=3">
        <img class="ring ring10 ring9" src="https://lashbrook.elikirk-dev.com/wp-content/uploads/2016/02/CC7CB15_METEORITEPOLISH001.png" alt="CC7CB15/METEORITE POLISH" data-link="store/catalog/product/view/id/84521/?base_metal=10&amp;inlay=29&amp;finish=18">
                                
        <div class="ring-data">
            <a class="ring-name" href="store/catalog/product/view/id/78841/?base_metal=10&amp;inlay=73&amp;finish=15">CC7.5FGEW2UMIL13/14KR HAMMER/POLISH</a>
            <a href="store/catalog/product/view/id/78841/?base_metal=10&amp;inlay=73&amp;finish=15" class="ring-link">View <i class="fa fa-caret-right"></i></a>
        </div>
    </div>
</div>
<script src="/wp-content/themes/rinzler/js/ringcollection.js"></script>
<script>

   var ringColl = new RingCollection(document.querySelector(".ring-collection"));

</script>