<?php

// @codingStandardsIgnoreFile

/** @var $block \Magento\GiftMessage\Block\Cart\Item\Renderer\Actions\GiftOptions */
if (!$block->isVirtual()): ?>
    <div id="gift-options-cart-item-<?php /* @escapeNotVerified */ echo $block->getItem()->getId() ?>"
        data-bind="scope:'giftOptionsCartItem-<?php /* @escapeNotVerified */ echo $block->getItem()->getId() ?>'"
        class="gift-options-cart-item">
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
            {
                "#gift-options-cart-item-<?php /* @escapeNotVerified */ echo $block->getItem()->getId() ?>": {
                    "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
                }
            }
        </script>
    </div>
<?php endif ?>
